"""users

Revision ID: 88e2debd87e1
Revises: f5a7f659ed40
Create Date: 2020-05-09 15:21:17.764560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e2debd87e1'
down_revision = 'f5a7f659ed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('classType', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'classType')
    # ### end Alembic commands ###
